export const GET_SWIMLANES_DATA_SUCCESS = 'GET_SWIMLANES_DATA_SUCCESS';
export const GET_TASKS_DATA_SUCCESS = 'GET_TASKS_DATA_SUCCESS';
export const HAS_ERRORED = 'HAS_ERRORED';
export const IS_LOADING = 'IS_LOADING';
